name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        drizzle-version: ["0.45.2", "beta"]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm add drizzle-orm@${{ matrix.drizzle-version }} -D --no-frozen-lockfile
      - run: pnpm run lint
      - run: pnpm run test
      - run: pnpm run build
